def print_number(num): #Выводит переданное число без перевода строки
    print(num,end="")
print_number(8)
print_number(8)
print_number(0)
print_number(0)
print_number(5)
print_number(5)
print_number(5)
print_number(3)
print_number(5)
print_number(3)
print_number(5)